name: tscore
description: "A live commentary and prediction app for cricket fans."
publish_to: "none"
version: 0.1.13+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  agora_rtc_engine: ^6.3.0
  app_settings: ^5.1.1
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.0.0
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10
  get_it: ^7.7.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  lottie: ^3.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  webview_flutter: ^4.0.0
  share_plus:
  url_launcher: ^6.1.5
  in_app_review: ^2.0.9
  in_app_update:

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - animation/
    - images/
    - images/icons/
